# flags:
#   ci:
#     paths:
#       - "gcov_lcov/*.h"
#       - "gcov_lcov/*.cpp"
#       - "gcov_lcov/tests/ci_test/*"
#   daily:
#     paths:
#       - "gcov_lcov/*.h"
#       - "gcov_lcov/*.cpp"
#       - "gcov_lcov/tests/daily_test/*"

# coverage:
#   status:
#     project:
#       default:
#         target: auto
#         threshold: 10%
#       ci:
#         target: 20%
#       daily:
#         target: 20%
#     patch:
#       default:
#         target: 90%
#       ci:
#         target: 100%
#       daily:
#         target: 100%

# flags:
#   ci:
#     paths:
#       - gcov_lcov/tests/ci_test/
#   daily:
#     paths:
#       - gcov_lcov/tests/daily_test/

# flag_management:
#   default_rules: # the rules that will be followed for any flag added, generally
#     # carryforward: true
#     statuses:
#       - type: project
#         target: auto
#         threshold: 10%
#       - type: patch
#         target: 90%
#   individual_flags: # exceptions to the default rules above, stated flag by flag
#     - name: ci  #fill in your own flag name
#       paths: 
#         # - "gcov_lcov/*.h"
#         # - "gcov_lcov/*.cpp"
#         - "gcov_lcov/tests/ci_test/*"
#       # carryforward: true
#       statuses:
#         - type: project
#           target: 20%
#         - type: patch
#           target: 100%
#     - name: daily #fill in your own flag name
#       paths: 
#         # - "gcov_lcov/*.h"
#         # - "gcov_lcov/*.cpp"
#         - "gcov_lcov/tests/daily_test/*"
#       # carryforward: true
#       statuses:
#       - type: project
#         target: 20%
#       - type: patch
#         target: 100%

# coverage:
#   status:
#     project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
#       default:
#         # basic
#         target: auto #default
#         threshold: 10%
#         base: auto 

# comment:                  #this is a top-level key
#   layout: " diff, flags, files"
#   behavior: default
#   require_changes: false  # if true: only post the comment if coverage changes
#   require_base: false        # [true :: must have a base report to post]
#   require_head: true       # [true :: must have a head report to post]
#   hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]

# flag_management:
#   individual_flags:
#     - name: ci
#       paths:
#         - gcov_lcov/tests/ci_test/*.cpp
#       statuses:
#         - type: project
#           target: 50%
#           threshold: 1%
#       carryforward: true
#     - name: daily
#       paths:
#         - gcov_lcov/tests/daily_test/*.cpp
#       statuses:
#         - type: project
#           target: 50%
#           threshold: 1%
#       carryforward: true

# 设置默认的覆盖率目标阈值
coverage:
  status:
    project: 
      default:      # 启用项目级的覆盖率目标
        target: 90%     # 设置全项目的覆盖率目标为 90%
        threshold: 1%   # 设置覆盖率波动的容忍度为 1%
      ci:
        target: 80%
        flags:
          - ci
      daily:
        target: 80%
        flags:
          - daily

comment:                  #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]

# 覆盖率报告中使用的不同的 flag
flags:
  ci         # 单元测试的覆盖率
    carryforward: true
  daily      # 集成测试的覆盖率
    carryforward: true

# # 需要排除的文件/目录
# ignore:
#   - "**/tests/*"           # 忽略所有测试目录中的文件
#   - "**/migrations/*"      # 忽略所有数据库迁移相关的文件

# # 覆盖率目标配置：为每个测试阶段设置不同的目标
# coverage:
#   flags:
#     ci:
#       target: 90%            # 单元测试的覆盖率目标为 90%
#     daily:
#       target: 85%            # 集成测试的覆盖率目标为 85%

# # 其他可选设置（例如覆盖率报告的更新方式）
# report:
#   base: false               # 禁止提交基于其他提交的合并覆盖率
#   update:
#     commit: true            # 提交时更新覆盖率数据

# # 用于覆盖率分析的报告类型
# coverage:
#   status:
#     patch: true             # 在每次拉取请求时启用覆盖率检查
#     changes: true           # 在每次代码变更时启用覆盖率变化检查
