# flags:
#   ci:
#     paths:
#       - "gcov_lcov/*.h"
#       - "gcov_lcov/*.cpp"
#       - "gcov_lcov/tests/ci_test/*"
#   daily:
#     paths:
#       - "gcov_lcov/*.h"
#       - "gcov_lcov/*.cpp"
#       - "gcov_lcov/tests/daily_test/*"

# coverage:
#   status:
#     project:
#       default:
#         target: auto
#         threshold: 10%
#       ci:
#         target: 20%
#       daily:
#         target: 20%
#     patch:
#       default:
#         target: 90%
#       ci:
#         target: 100%
#       daily:
#         target: 100%

# flags:
#   ci:
#     paths:
#       - gcov_lcov/tests/ci_test/
#   daily:
#     paths:
#       - gcov_lcov/tests/daily_test/

# flag_management:
#   default_rules: # the rules that will be followed for any flag added, generally
#     # carryforward: true
#     statuses:
#       - type: project
#         target: auto
#         threshold: 10%
#       - type: patch
#         target: 90%
#   individual_flags: # exceptions to the default rules above, stated flag by flag
#     - name: ci  #fill in your own flag name
#       paths: 
#         # - "gcov_lcov/*.h"
#         # - "gcov_lcov/*.cpp"
#         - "gcov_lcov/tests/ci_test/*"
#       # carryforward: true
#       statuses:
#         - type: project
#           target: 20%
#         - type: patch
#           target: 100%
#     - name: daily #fill in your own flag name
#       paths: 
#         # - "gcov_lcov/*.h"
#         # - "gcov_lcov/*.cpp"
#         - "gcov_lcov/tests/daily_test/*"
#       # carryforward: true
#       statuses:
#       - type: project
#         target: 20%
#       - type: patch
#         target: 100%

coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        # basic
        target: auto #default
        threshold: 10%
        base: auto 

# 需要排除的文件/目录
ignore:
  - "**/tests/**"           # 忽略所有测试目录中的文件
  - "**/py-cov/*"           # 忽略所有测试目录中的文件
  - "**/migrations/*"      # 忽略所有数据库迁移相关的文件

comment:                  #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]

flag_management:
  individual_flags:
    - name: ci
      paths:
        - gcov_lcov
      statuses:
        - type: project
          target: 50%
          threshold: 1%
      carryforward: true
    - name: daily
      paths:
        - gcov_lcov
      statuses:
        - type: project
          target: 50%
          threshold: 1%
      carryforward: true
