flags:
  ci:
    paths:
      - "gcov_lcov/*.h"
      - "gcov_lcov/*.cpp"
      - "gcov_lcov/tests/ci_test/*"
  daily:
    paths:
      - "gcov_lcov/*.h"
      - "gcov_lcov/*.cpp"
      - "gcov_lcov/tests/daily_test/*"
